### ISSUE TITLE
Implement "lazy" views

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-elmish#2]
Elm can avoid vdom reconciliation by implementing `lazy` function, Elmish should be able to do that as well.

**Comment by alfonsogarciacaro** [comment]
Note that F# `lazy` operator is [implemented in Fable](https://github.com/fable-compiler/Fable/blob/master/src/tests/TypeTests.fs#L247), so you can use it if needed :+1:

**Comment by et1975** [comment]
I haven't looked at Elm's impl yet, but I think it's different from F#'s semantically - in Elm it's a function of inputs, and is more like memoize that works with the last known value only.

**Comment by et1975** [comment]
experimental impl is in fable-elmish-react@0.1.1
