### ISSUE TITLE
Cmd.OfAsync should report exceptions somehow, at least from `ofError`

### ISSUE THREAD

**Issue by reinux** [fable-compiler/fable-elmish#204]
### Description

This may be specific to Elmish.React, but `Cmd.OfAsyncImmediate` eats exceptions, whether it's just happening in the actual async or it's reraised from `ofError`.

This had me baffled for a good chunk of the day.

Exceptions elsewhere are reported in the developer console in the case of Elmish.React. I think the same should happen for commands.

### Repro code

```
async {
  failwith "This exception won't be seen"
} |> Cmd.OfAsyncImmediate.result getInit

(fun _ -> async {
  failwith "This exception won't be seen either"
}) |> Cmd.OfAsyncImmediate.attempt getInit () raise
```

### Related information 

* elmish version: 3.0.6
* fable-compiler version: 2.10.1
* fable-core version: 3.1.5
* Operating system: Windows 10 Pro 1909

**Comment by et1975** [comment]
Thanks for reporting this.
Yes, it should report the exceptions. I don't use Async commands in Fable apps myself, but I'll try to get some tests going.

**Comment by et1975** [comment]
The `ofError` throwing exceptions is not handled because of [this Fable issue](https://github.com/fable-compiler/Fable/issues/2115), so don't recommend throwing from there.
`Cmd.OfAsyncImmediate.result` swallowing the exception should be fixed, please give 3.1.0 a spin.

**Comment by reinux** [comment]
Hm... Still seems to be eating the exception.

```
  let getInit =
    fun _ -> (async {
    let! user = Async.AwaitPromise (userManager.getUser ())
    if user = null then
      console.log "Throwing"
      failwith "User not logged on"
      userManager.signinRedirect()
  Loading, Cmd.OfAsyncImmediate.result (getInit ())
```

![image](https://user-images.githubusercontent.com/5127297/87234407-5d345980-c385-11ea-86dd-a8027f822048.png)

**Comment by et1975** [comment]
That would be the same Fable issue then, since I'm not swallowing the
exception in the command anymore. You can handle the exception in the CE
yourself though. In general the guidance is not to rely on the dispatch
loop handling it for you.
Also, since you are using promise, just use the promise command/CE instead.

**Comment by reinux** [comment]
Fable.SimpleHttp uses async, so that's what I'm using.

But yeah, I'll just wrap it in something to print to the console for now. It's just for dev/debugging anyway.

Thanks for looking into this and for posting the issue on Fable!
