### ISSUE TITLE
Obsolte all Cmd.XXX.result functions 

### ISSUE THREAD

**Issue by et1975** [fable-compiler/fable-elmish#207]
This seems like it was a bad idea. See #204 for example of people misusing it - the same error on CLR would have crashed the process. The only safe version of the `result` is `Cmd.ofMsg`, which we'd keep. 

I'm thinking to obsolete these functions in 4.x and remove in subsequent major release.

@MangelMaxime @alfonsogarciacaro and co. any thoughts or concerns?

**Comment by MangelMaxime** [comment]
The only reason, I see for using `result` is if people don't care to be notified in case of success or error which seems a bit strange to me ^^.

So IHMO we make them obsolete or make them handle the exception "correctly" like `perform` does just to avoid a potential crash.

Personally, I am not a big fan of `result` variant and I am ok with removing them.

**Comment by reinux** [comment]
Ha! I just looked at the source for `Cmd` and I finally understand what `perform` does.

There's a good chance that this has been a PEBKAC issue specific to me, but could I suggest that the documentation elaborate a little more on these functions?

Something like:

```
       /// Command that will evaluate an async block.
       /// Maps the success and discards any exceptions.
        let perform (start: Async<unit> -> unit) ...

```

Knowing that, I'm also in favor of obsoleting `result`.

Also, I do still think it would be useful for `perform` to log to console, at least when the debug flag is set. For my use case (downloading user details for `init`), it has the same effect of silently crashing my app as `result` does. Granted, I probably should have used `either` and handled the error to begin with 😄

**Comment by TysonMN** [comment]
> ...at least when the debug flag is set.

What debug flag?

**Comment by reinux** [comment]
I guess they're called constants?

This thing in the .fsproj:     `<DefineConstants>DEBUG; TRACE</DefineConstants>`

As in, something along the lines of...

```
#if DEBUG
#if FABLE_COMPILER
console.log ...
#else
System.Console.Error ...
#endif
#endif
```

**Comment by et1975** [comment]
Addressed in v4 beta-2
