### ISSUE TITLE
Change timer interval to a greater value than 0

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/fable-elmish#209]
I have noticed below code sets the timer to 0
https://github.com/elmish/elmish/blob/b4304107342d8689ec9b97b2a9d2929857281a96/src/cmd.fs#L137
While it works fine for fable actually "0" is not even valid value for Timer. If in future fable guys implement the spec, that line will break.

**Comment by et1975** [comment]
Addressed in v4 beta-2

**Comment by OnurGumus** [comment]
@et1975 will this not cause an artificial delay?
let start x = Timer.delay 100 (fun _ -> Async.StartImmediate x)

**Comment by et1975** [comment]
Good catch - misread the docs, 100ms is the default, not the minimum. Updated and will release with the next beta.
Thanks!
