### ISSUE TITLE
Messages are not dispatched after App restart

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-elmish#21]
1) clone https://github.com/fable-compiler/fable-react_native-demo
2) start app
3) after short syncinf you will see something like the following:
![image](https://cloud.githubusercontent.com/assets/57396/20827833/926ce984-b874-11e6-9d84-57ed650b8451.png)
4) use back button to leave app
5) go back to app via android menu
6) you will see:
![image](https://cloud.githubusercontent.com/assets/57396/20827856/af86f87a-b874-11e6-8752-61c98edd1b7f.png)

Note that it did not sync and you see no "Locations: 3" at the bottom.

This is because the very first message from the init() function doesn't get dispatched.

This worked before the fable 0.7 update wave.

**Comment by et1975** [comment]
Thanks for the detailed report!
The problem isn't that init wasn't called, it's that the app is "tombstoned". With RN 0.36 and later I no longer have access to the api I was using to create root component and the new implementation had to handle the unmount event for this specific scenario to work.

Fixed and release as "stable" 0.7.1, let me know how it goes.

**Comment by forki** [comment]
seems to work. Thanks a ton!
