### ISSUE TITLE
Add Program.run variant that splits between first render and run program loop

### ISSUE THREAD

**Issue by Tarmil** [fable-compiler/fable-elmish#210]
I have an issue with Bolero component lifecycle and I think this small change is the only way to fix it.

In Blazor, component lifecycle is handled via a number of methods, including these:
* `OnInitialized` is called before the first render, including during server-side prerender.
* `OnAfterRenderAsync` is called after every render, and receives a boolean that is true if this was the first render.

Bolero calls `Program.runWith` inside `OnInitialized`, but this causes problems. The main issue is that the program loop ends up being run during prerender. So for example, if you set up a timer in `Program.withSubscribe`, then [it will tick on the server](https://github.com/fsbolero/Bolero/issues/166). What we would need to do instead is do the initial render in `OnInitialized`, and run the program loop in `OnAfterRenderAsync(true)`.

I have been trying [a simple change to Elmish](https://github.com/Tarmil/elmish/commit/b135fa9b6aba112d50fb4a78fc9db36f982a4ea0) that allows this split, and it fixes the issue nicely.

**Comment by et1975** [comment]
Thanks for bringing this up. The solution you are thinking would help with
inital subscriptions, but i think in practice more often subs are created
after the initial setup due to the need to access latest model state.
There are a couple of different ways in the works to help with situation
like this - termination condition and subscriptions that could be
cancelled/changed after they are setup. I don't have the time-frame for the
release of v4 though, maybe see if you can implement your workaround in
bolero for now?

**Comment by Tarmil** [comment]
Yeah I can implement it in Bolero. It's quite clunky though, because I need access to a bunch of private stuff. I end up [abusing `Program.map` and entirely duplicating the ring buffer](https://github.com/fsbolero/Bolero/blob/fix/prerender-subscribe/src/Bolero/ProgramRun.fs) :/

> termination condition and subscriptions that could be cancelled/changed after they are setup

Those will definitely be useful. I'd still appreciate a way to not start the subscriptions in the first place though :)

**Comment by et1975** [comment]
@Tarmil v4 beta is released with termination support, see if it works for you?

**Comment by et1975** [comment]
@Tarmil  Here's an idea: now that subscriptions get latest model, would it make sense to wrap the program (like browser/navigation does) and control what happens when that way?

**Comment by kspeakman** [comment]
Not sure if it will work for your use case, but you could skip Program and just call your own app init and view fns.

```fsharp
let initialRender =
    let model, _cmd = App.init initArg
    App.view model (fun _ -> ())
```

**Comment by Tarmil** [comment]
@kspeakman This is a library component that receives a Program from its caller, so I can't directly call the declared init and view functions, but I should be able to extract them from the Program, so this might work indeed.

**Comment by Tarmil** [comment]
@kspeakman After thinking about it some more, unfortunately that's not ideal either.

Ideally we would be able to do something like "If this is a prerender, then call init and view explicitly, else this is a page startup so call Program.run". Unfortunately, inside `OnInitialized`, we don't know whether we're prerendering or starting up the full page. So we can't make this choice. The best we could do would be to call init and view in `OnInitialized` and Program.run in `OnAfterRender`; but then, init and run would be run twice during page startup, which is not great for performance.

**Comment by kspeakman** [comment]
@Tarmil I wanted to be sure I understand your scenarios. Please correct me.

| scenario | desired process |
|--|--|
| prerender | * create the model, but ignore cmds<br> * render the model w/o event handlers |
| start prerendered | * mount DOM element, attach event handlers (how?)<br> * create model (or receive from server)<br> * No render<br> * run Cmd |
| start fresh | normal Elmish program flow |

I noticed in the docs that `prerendered` is the hosting option. (In razor pages, maybe it's controlled by `render-mode="ServerPrerendered"` or Static?) I'm guessing this data is impractical to plumb into OnInitialized? I apologize as I'm sure this question shows my ignorance of Blazor.

**Comment by et1975** [comment]
I believe state-driven subscriptions now offers an ideal way for a view implementor to delay/control what should happen when. If not, please reach out to re-open the discussion.

**Comment by Tarmil** [comment]
Blazor in .NET 9 is finally adding [a property that indicates whether the render mode is interactive](https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview5/aspnetcore.md#detect-the-current-component-render-mode-at-runtime). With this we'll be able to completely bypass this issue by simply calling either `Program.run` in interactive mode, or `Program.init` and `Program.view` in static mode.
