### ISSUE TITLE
list ctor is nolonger compiling as Cmd

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-elmish#212]
### Description

For js interop we use a the old pattern of `[fun dispatch -> doSomething dispatch) ]`. This no longer compiles in alpha channel. Is there a replacement? Maybe a static function on the Cmd module which takes a `Dispatch<'Msg> -> unit` or something like that?

### Repro code

![image](https://user-images.githubusercontent.com/57396/97146898-eae75980-1768-11eb-9d26-a204073ecf59.png)

### Related information 

* elmish version: 4.0.0-alpha-2
* fable-compiler version: nagareyama

**Comment by Zaid-Ajaj** [comment]
Maybe Cmd.ofSub if it is still around

**Comment by forki** [comment]
yes I think that's the correct one. thanks

**Comment by forki** [comment]
@Zaid-Ajaj  I guess you also want to update: https://github.com/Zaid-Ajaj/Elmish.Toastr/blob/master/src/Elmish.Toastr.fs#L182  ;-)

**Comment by et1975** [comment]
Please don't build anything important off the alfa bits :), that's for experimentation and getting the feedback. Specifically anything about `Sub` is subject to change.

**Comment by forki** [comment]
understood ;-)
