### ISSUE TITLE
Cleaner console tracing

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-elmish#214]
Because Elmish messages can be quite buried in the state hierarchy, I wrote a tracer that unwraps the unions and puts the union fields in a JS object so they look better in the browser console.

![image](https://user-images.githubusercontent.com/8275461/106426359-cce86e00-64a8-11eb-8412-241010f4b8ea.png)

I put [the code here](https://gist.github.com/alfonsogarciacaro/85a79f75b01d3e554a88d2a054d1e002) but some people asked to include it in Elmish by default. The thing is this is a bit Fable/browser specific so if you're ok with adding it to Elmish I have a couple of questions:

- Replace the current `withConsoleTrace` or offer it as an alternative?
- Do this only for Fable (with `#if FABLE_COMPILER`) or adapt it so it looks somewhat similar in .NET console?

> Btw the elmish/debugger already did something like this. But the Redux devtools browser extension seems to be dead so I don't know if many people are still using it.

**Comment by et1975** [comment]
`#if` seems fine for starters

**Comment by AlbertoDePena** [comment]
Will this enhanced logger be included in the library?

**Comment by et1975** [comment]
Sure, a PR would be appreciated. Alternatively, would it work as react/browser impl that plugs into `trace` [here](https://github.com/elmish/elmish/blob/v4.x/src/program.fs#L81)? Since we're making breaking changes to the API might as well adjust this signature if needed.

**Comment by AlbertoDePena** [comment]
I was thinking of maybe including an extra module... Something like this:

```F#
namespace Elmish

open Elmish

[<RequireQualifiedAccess>]
module Tracers =

open System
open Fable.Core

let getMsgNameAndFields (t: Type) (x: 'Msg) : string * obj =
    let rec getCaseName (t: Type) (acc: string list) (x: obj) =
        let caseName = Reflection.getCaseName x

        let uci =
            FSharp.Reflection.FSharpType.GetUnionCases(t)
            |> Array.find (fun uci -> uci.Name = caseName)

        let acc = (Reflection.getCaseName x) :: acc
        let fields = Reflection.getCaseFields x

        if fields.Length = 1 && Reflection.isUnion fields.[0] then
            getCaseName (uci.GetFields().[0].PropertyType) acc fields.[0]
        else
            // Case names are intentionally left reverted so we see
            // the most meaningful message first
            let msgName = acc |> String.concat "/"

            let fields =
                (uci.GetFields(), fields)
                ||> Array.zip
                |> Array.map (fun (fi, v) -> fi.Name, v)
                |> JsInterop.createObj

            msgName, fields

    if Reflection.isUnion x then
        getCaseName t [] x
    else
        "Msg", box x

/// Use it when initializing your Elmish app like this
/// |> Program.withTrace Tracers.console
let inline console (msg: 'Msg) (state: 'State) =
    let msg, fields = getMsgNameAndFields typeof<'Msg> msg
    JS.console.log (msg, fields)
    JS.console.log ("Updated State", state)

```

That way many more can be built. Perhaps one for Application Insights...

**Comment by et1975** [comment]
If this goes into [elmish/browser](https://github.com/elmish/browser) then it will do nicely.

**Comment by AlbertoDePena** [comment]
@et1975 

Are you saying you want the PR in the `elmish/browser` code repository? not in the `elmish/elmish` repo? Can you let me know your reasoning as to why?

Thanks =)

**Comment by MangelMaxime** [comment]
@AlbertoDePena 

> Can you let me know your reasoning as to why?

My supposition is the following:

The tracing proposed in this PR is relying on specific feature of the Browser (`console.log`, which allows to explore the provided POJO).

The code in `elmish/elmish` support both Fable and .NET runtime, so introducing something that is using Browser behaviour is not really possible.

**Comment by AlbertoDePena** [comment]
@MangelMaxime 

That makes sense =)

**Comment by et1975** [comment]
Will be tracked in https://github.com/elmish/browser/pull/48

**Comment by et1975** [comment]
I think the implementation is fairly fable/js specific and I'd like to keep
the core of elmish lean and cross-platform. Browser is a platform specific
extension. Alternatively Debugger is reimplemented w/o JS dependencies.
