### ISSUE TITLE
Invalid value '0' for parameter 'interval' when using Elmish with .net 5 and an async function

### ISSUE THREAD

**Issue by rabejens** [fable-compiler/fable-elmish#218]
### Description

When I want to call an async function with `Cmd.OfAsync`, I get an exception `Invalid value '0' for parameter 'interval'`.

This happens when using Elmish in a .net 5.0 project. It comes from the following bit of code:

```fsharp
#if FABLE_COMPILER
        let start x = Timer.delay 0 (fun _ -> Async.StartImmediate x)
#else
        let inline start x = Async.Start x
#endif
```

Here, a `System.Timers.Timer` with an interval of 0 is started, which doesn't work.

### Repro code

```fsharp
open Elmish

type State =
     | DontKnowTheAnswer
     | FindingTheAnswer
     | TheAnswerIs of int

type Message =
     | FindTheAnswer
     | TheAnswerIs of int

let findTheAnswerAsync() = async { return 42 }

let init() = DontKnowTheAnswer, Cmd.none

let update findTheAnswerAsync msg _ =
    match msg with
    | FindTheAnswer ->
        let cmd = Cmd.OfAsync.perform findTheAnswerAsync () Message.TheAnswerIs
        State.FindingTheAnswer, cmd
    | TheAnswerIs a ->
        State.TheAnswerIs a, Cmd.none

[<EntryPoint>]
let main argv =
    let update' = update findTheAnswerAsync
    let view model dispatch =
        match model with
        | DontKnowTheAnswer ->
            printfn "I don't know the answer. Let's find it."
            dispatch FindTheAnswer
        | FindingTheAnswer ->
            printfn "We are finding the answer."
        | State.TheAnswerIs a ->
            printfn "The answer is %d" a
    Program.mkProgram init update' view |> Program.run
    0 // return an integer exit code
```

Put this in a console app that is targeting .net 5.0.

#### Expected

State should be `TheAnswerIs 42`

#### Actual:

`ArgumentException` is thrown

### Related information 

* elmish version: 3.1.0
* fable-compiler version: None
* fable-core version: 3.2.6
* Operating system: Windows

**Comment by MangelMaxime** [comment]
Hello, 

are you compiling using Fable or using standard `dotnet build` command?

If you use Fable, I suppose the error you are seeing is coming from

https://github.com/elmish/elmish/blob/d84398f7568b547bb6ef993ba9f2d429887ae20d/src/prelude.fs#L27-L35

which should works as we are casting the `0` as a `float` value.

Also which package are you using? Are you using `Fable.Elmish` or `Elmish` ?

**Comment by et1975** [comment]
I was just about to ask the same thing as @MangelMaxime , I suspect you're trying to use Fable.Elmish lib to target CLR. Use Elmish package for CLR and Fable.Elmish for Fable projects.

**Comment by rabejens** [comment]
Yes I use `Fable.Elmish` instead of `Elmish`.

Replacing the dependencies solved the problem. Thanks!
