### ISSUE TITLE
Selective throttling in Elmish

### ISSUE THREAD

**Issue by tomcl** [fable-compiler/fable-elmish#219]
### Description

I have an application use case not (I think) currently supported by Elmish and would like to discuss how this could be supported.

If I am misunderstanding something this will have a quick answer!

Related issues:
Discussion of throttling & limiting & debouncing
https://www.gitmemory.com/issue/elmish/elmish/189/530080466
https://github.com/elmish/elmish/issues/189

Use case.

This is a graphical drawing program that allows symbols to be placed and moved on an SVG canvas. Symbols have connections that intelligently route in response to movements.

Written using elmish there are two potential performance issues: view function time, and update time. Using `Elmish.withReactBatched` deals with problems due to the view function being called too often. however it leaves problems due to the update function being called too often.

This happens because updates are made in response to mouse movements. Normally the code is fast, and every mouse move event can be captured and processed. However, when moving a large number of objects at once this leads to most CPU time being taken processing queued mouse messages.

Neither throttling, limiting, or debouncing fit this problem, because we only want to limit messages when there is not enough time to process them. in fact the behaviour required is the input-side analog of withReactBatched. 
(1) if the message queue contains one message process it as normal
(2) if the message queue contains multiple messages extract them all, apply an application-dependent message reduction function, and insert the result into the queue, passing the first generated message to update.

In the case of mouse moves (ubiquitous) the message reduction function would delete all mouse move operations except the last one (assuming the mouse moves are represented using absolute not relative coordinates).

It is not possible easily to implement this from outside Elmish without some extra way to interact with the command queue?

This type of selective throttling is absolutely needed for the common use case of cpu-intensive rendering that changed with mouse position. Which makes me think i am missing something? But I cannot see how to do it with Elmish as is.

## Semantics & rationale

The semantics _wanted_ from selective throttling makes sense when operations are associative, or _nearly_ associative, with a suitable adaptor function. The idea is that a sequence of updates:

`msg1, msg2, msg3....`

Can be transformed into an equivalent shorter sequence by application of a `partialReduce` function to a subsequence of the messages:

`partialReduce: [msg1;msg2;msg3] -> [msg1']`

in general:

`partialReduce: Msg list -> Msg list`  where the output list is shorter than the input one (and typically of length 1).

Such a function then needs to be applied to the messages in the message queue at the time the command loop is ready to process the next message in the case the queue contains more than one message.

Without this external message sources - such as mice - can easily, and quite unnecessarily, saturate the MVU loop.

Providing a callback to process the message queue whenever a new message is read would do this. preferably the callback would be called only in the case that multiple messages exist in the queue, with the list of queued messages, and would return the contents of a new queue, which would replace the old one (this would be done via push and pop so that new messages entering the queue from external events are unaffected and ordered after the result messages).

**Comment by tomcl** [comment]
Perhaps better, this same functionality could be incorporated into the update function, but only if it had access to the number of items in the message queue - when that is > 1 update would "swallow" messages, holding onto them in Model state so they can be combined with a subsequent message.

All that is required for this is exposing the message queue length. Maybe this is possible?

**Comment by et1975** [comment]
I've had something similar done for large stream of events coming in over sockets. Don't have the access to the code right now, but the idea is to setup an intermediary queue where you get the chance to reduce/aggregate/project before handing the event that you want processed to elmish. In my case I could setup aggregation window and emit an event upon the window closing, for example  setting the window to 1 sec, I'd emit at most one message that I picked/built from all the inputs in that window. Your case seems more complicated since you're looking for backpressure. 
Currently you can do that with `Cmd.ofSub`: store the marker of the last processed message in the model (timestamp, id, whatever makes sense) and looking at that determine if you should emit the next message or not.

**Comment by tomcl** [comment]
Yes, that is an idea but still not quite right, because the back-pressure indication is delayed by 1 message.

EDIT: ok - I guess you could at least prevent messages from building up too much. But it is not ideal.

**Comment by tomcl** [comment]
Why not just expose the message queue length?

**Comment by tomcl** [comment]
Or, another perhaps even nicer way to do this would be to have a version of `program` that accepts an update function with input a list of messages. The update function is then called with all outstanding messages in the queue.

**Comment by tomcl** [comment]
Solved!

@et1975 not sure if this is related to what you did.

I guess the reason for not doing this is that if you double the number of messages, you can do it with Elmish as it stands. 

```
let update msg model  =
    match msg with
    | msg when canBeCombined msg-> 
        {model with MsgLst = msg :: model.MsgLst}, Cmd.ofMsg (ExecuteMsgs (model.MsgLst.Length+1))

    | ExecuteMsgs numMessages when model.MsgLst.Length = numMessages -> 
        // execute the messages in model.MsgLst and empty it. This includes all outstanding messages, 
        // because they will be before the ExecuteMsgs message in the queue

    | ExecuteMsgs _ -> 
                       // do nothing - in this case another message was in the queue - 
                       // it will have its own ExecuteMsgs message

    | _ -> // other messages
```

I _think_ this will do what I've asked for!

**Comment by et1975** [comment]
I was talking about tackling this by batching at the source - have a window and collect all/relevant events during that window, then send them to elmish as one event, but your method would work as well. I'd consider making the window max-timed though, cause if your source dries up you'd still want the processing to happen.

**Comment by tomcl** [comment]
OK, yes.

It is Ok - what I did not realise is that what I want can be done with no delay. The execute message will always come back (immediately if there are no other messages) and so there is no delay. It is effectively the same as having an update function that is given the list of all outstanding messages currently in the queue to process.

Quite surprising this can be done...
