### ISSUE TITLE
Program.toNavigable doesn't exist when building for production

### ISSUE THREAD

**Issue by jacentino** [fable-compiler/fable-elmish#223]
### Description

I have an application using Program.toNavigable. There is a corresponding code in App.fs

`Program.mkProgram Pages.init Pages.update Pages.view`
`|> Program.withSubscription Pages.subscribe`
**`|> Program.toNavigable Pages.urlParser Pages.urlUpdate`**
`#if DEBUG`
`|> Program.withConsoleTrace`
`#endif`
`|> Program.withReactSynchronous "elmish-app"`
`#if DEBUG`
`|> Program.withDebugger`
`#endif`
`|> Program.run`

When building it in development mode with `fake build -t run` command it compiles and executes properly.
When building for production with `fake build` command, compilation fails with the following message:

ERROR in ./src/Client/App.fs
Module Error (from ./node_modules/fable-loader/index.js):
C:/Projekty/FSharp/Quatera/src/Client/App.fs(16,12): (16,23) error FSHARP: The value, constructor, namespace or type 'toNavigable' is not defined. (code 39)

If I rewrite the code to not use `Program.toNavigable`, it compiles and executes.

I didn't change anything in a build script, so I assume, that it's not my fault.

### Repro code

1. Prepare project, that uses `Program.ToNavigable`
2. Build with `fake build` command

### Expected and actual results

For now, my project builds only in development mode.
It should be possible to build for production.

### Related information 

* elmish version: 3.1.0
* fable-compiler version: 2.10.2
* fable-core version: 3.1.5
* Operating system: Windows 10

**Comment by et1975** [comment]
It seems you are using fable2 complier, you should upgrade to table3
otherwise it might be difficult to pinpoint the source of the problem.

**Comment by MangelMaxime** [comment]
Hello @jacentino,

can you please show us your `open` statements?

I suspect you have have something like that:

```fs
open Elmish
open Elmish.React
#if DEBUG
open Elmish.HMR
#endif

// ...
```

If that's the case, you should let `open Elmish.HMR` always open because the library is already taking care of handling production VS debug environment.

https://github.com/elmish/hmr/blob/6a560e1bb70e003d25f0a8aaba694f7b7d091228/src/hmr.fs#L168-L183

If you really want to handle it yourself you need to make sure to have the module `Elmish.Navigation` open in production mode.

**Comment by jacentino** [comment]
Hello Maxime,

I moved Elmish.HMR outside condition and now everything works well.
Thank you

@et1975 I'll definitely upgrade the compiler to v3.
