### ISSUE TITLE
Can multiple Elmish "programs" be instantiated in a single application?

### ISSUE THREAD

**Issue by BentTranberg** [fable-compiler/fable-elmish#225]
This is a question about how Elmish can be used. I am thinking about using Elmish in servers, with no views, just to benefit from the state machine and messaging. I have just now started experimenting with the Elmish library.

My idea is to wrap a viewless Elmish "program", like this here

```
    Program.mkProgram init update view
    |> Program.withSubscription (fun initialModel -> timer initialModel)
    |> Program.run
```
inside a MailboxProcessor. This again will likely be wrapped in a class, probably named Actor, that will take care of starting, stopping, communication with the world, etc.

The point is to be able to instantiate several Elmish programs, or in other words run the snippet above inside several MailboxProcessors.

My question is very simple: Is there any reason this won't work?

**Comment by BentTranberg** [comment]
Just to see what happened, I did this, and processing, also involving some timers and dispatching test messages, worked well in both instances in parallel. Still, before progressing with any large scale development, it would be nice to know if it's supposed to work as explained above.

```
let view (m: Model) (dispatch: Dispatch<Msg>) = printfn "%A\n" m

[<EntryPoint>]
let main argv =
    Program.mkProgram init update view
    |> Program.withSubscription (fun initialModel -> timer initialModel)
    |> Program.run
    Program.mkProgram init update view
    |> Program.withSubscription (fun initialModel -> timer initialModel)
    |> Program.run
    Console.ReadKey() |> ignore
    0
```

**Comment by Nhowka** [comment]
On Elmish.Bridge we create a loop for every new connected client. There we also have support for named bridges for connecting on different programs on different endpoints supporting different models, so I believe there shouldn't be a problem on your use case.

**Comment by BentTranberg** [comment]
Thank you very much. It didn't occur to me that the answer to this question might be buried in the source of Elmish.Bridge, which seems very obvious now that you mention it. By the way, this idea seems like a simple, quick and low risk migration path towards use of Elmish.Bridge in the system I'm working on, either everywhere or where Elmish GUI clients are involved. I already have actors and communication I've made myself, so now just getting more uniform and flexible state machines with Elmish inside the actors.

I'll wait a couple of work days into the week before closing this issue, in case others have something to add. But feel free to close before I do.

**Comment by et1975** [comment]
Yes, it is perfectly safe to run multiple instances of elmish programs in
parallel.
However, it's not safe to use elmish as the backend message processor:
https://thoughtspam.wordpress.com/2018/08/14/naive-agent-based-backends/

**Comment by BentTranberg** [comment]
Thanks for the go-ahead and the link. The actors running elmish programs will only run separate complex business logic that can be expressed as a hierarchy of state machines. They will not be doing any direct IO or any other kind of non-business logic themselves, but will have to talk through other actors not running elmish programs in order to deal with the world outside of the server - database, files, GUI, industrial equipment. I have not yet come to a conclusion whether this is a good idea - I need more experience using it for various kinds of business logic - but I do have the new Actor class that runs non-view elmish programs working now.
