### ISSUE TITLE
Expose Program module functions as C#/VB compatible extension methods

### ISSUE THREAD

**Issue by xperiandri** [fable-compiler/fable-elmish#226]
### Description

Using Elmish in Elmish.Uno library I must instantiate the ELmish program in C# because UWP does not support F# at all and Xamarin uses old project format with F# which is unusable.
Hence in order to subscribe an Elmish program to platform-specific events, I need to call `withSubscription`/`withSetState` from C#

### Related information 

* Elmish version: 3.1.*

**Comment by et1975** [comment]
Totally reasonable request, but I think it needs its own library. As
someone who has all the details of the use-case, would you be willing to
contribute one?

**Comment by xperiandri** [comment]
Do you mean adding a separate project to this repository that you will publish as a separate NuGet?

**Comment by et1975** [comment]
If you like I can be a co-owner, but you could publish it yourself.

**Comment by xperiandri** [comment]
Is it too much for a single class with a few methods?

**Comment by et1975** [comment]
The questions to me is not how many abstractions being added, but do they belong in the core and do I want to maintain them going forward. 
Incidentally, the name escapes me right now, but there was a project here on github where entire elmish is reimplemented in C# and maybe that would be a better fit in your case? I'm just thinking with the lack of DUs `update` will look somewhat different, w/o `(>>)` invoking to child views will be different. I just feel like having a simple way to start a program from C#/VB would be a niche and might just grow into whole host of shims and adapters to be broadly useful - which would be better served by a separate repo and an invested owner.

**Comment by xperiandri** [comment]
```fs
open System
open System.Runtime.CompilerServices
open Elmish

[<AbstractClass; Extension>]
type ProgramExtensions =

    [<Extension>]
    static member WithSetState (program, setState) =
        Program.withSetState setState program

    [<Extension>]
    static member WithSubscription (program, subscribe) =
        Program.withSubscription subscribe program

    //[<Extension>]
    //static member WithSetState (program, setState : Action<'model, Dispatch<'msg>>) =
    //    Program.withSetState (setState |> FuncConvert.FromAction) program

    //[<Extension>]
    //static member WithSubscription (program, subscribe : Func<'model, Cmd<'msg>>) =
    //    Program.withSubscription (subscribe |> FuncConvert.FromFunc) program
```
