### ISSUE TITLE
Cmd helpers for checking success by option

### ISSUE THREAD

**Issue by LyndonGingerich** [fable-compiler/fable-elmish#254]
I wrote this code for my own use and wondered if the project would benefit from it. It seems to work in my own project so far. Would these helpers help others? If so, how should they be named and namespaced?

```fsharp
module Cmd =
  module OfFuncOption =
    let either (task: 'a -> _) (arg: 'a) (ofSuccess: _ -> 'msg) (ofError: _ -> 'msg) : Cmd<'msg> =
      let bind dispatch =
        match task arg with
        | Some a -> a |> ofSuccess
        | None -> arg |> ofError
        |> dispatch

      [ bind ]

    let attempt (task: 'a -> _) (arg: 'a) (ofError: _ -> 'msg) : Cmd<'msg> =
      let bind dispatch =
        match task arg with
        | Some _ -> ()
        | None -> arg |> ofError |> dispatch

      [ bind ]
```

**Comment by MangelMaxime** [comment]
Hello,

I think this is a specific use case that you have and don't think we will include it in the core module. Please @et1975 can correct me, if you think we should.

If you want to share it with others, you can create a Gist so people can include it using Paket or release your helpers as a separate package that people can include to opt-in the support of such helpers.

**Comment by LyndonGingerich** [comment]
Got it. I was thinking that, since F# authors often use functions that return options rather than throwing exceptions, they might do so here as well. I'll just make a repo or a Gist.

**Comment by LyndonGingerich** [comment]
~~https://gist.github.com/LyndonGingerich/e10df3baf5af75c5d0d8b7cbeefcd4c5~~ (removed since I realized that my solution didn't still catch exceptions)

**Comment by Luiz-Monad** [comment]
> Got it. I was thinking that, since F# authors often use functions that return options rather than throwing exceptions, they might do so here as well. I'll just make a repo or a Gist.

You might want to look at this, it has lots of helpers to make connecting things easier. https://github.com/haf/YoLo/blob/master/YoLo.fs
