### ISSUE TITLE
Issue with elmish on IE11 and below

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-elmish#26]
We use fable elmish-react for our website and it works mostly fine.

But in IE we have a strange issue. When you click a navigation link then the adress bar changes, but the site content remains the same until you press F5.

@MangelMaxime looked at our code and found that something is using the 'popstate' event.
He found a bug report - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3740423/
It's marked as resolved but we don't know for which version of IE.

He also sad that Fable-Arch is using the 'hashchange' event because it's working across all the browsers.

@et1975 any chance to change that?

**Comment by et1975** [comment]
Thanks, I'll take a look.

**Comment by et1975** [comment]
https://github.com/browserstate/history.js

I don't have IE to try this on, but could you give the polyfill a spin instead? If you take a look at the nav sample, it already includes `fetch` polyfill (for safari compat), this would be similar.

**Comment by forki** [comment]
JsInterop.importAll "whatwg-fetch" <- this?

how would the other polyfill look like? could you add it to the sample?

**Comment by forki** [comment]
OK I tried to add the jquery and also the native polyfill by copying the js files to our suave server and referencing it from index.html.

Basically the same way as @alfonsogarciacaro explained to me for core-js shim.

But this has no effect ;-(

**Comment by et1975** [comment]
Yeah, I'm not having any success so either. Tried two polyfills already. 

Thing is, just listening to `hashchange` introduces a problem: duplicate events where `popstate` works, while just listening to `hashchange` might exclude urls that are not hash-prefixed (and currently work with `poststate`)...

I'll figure something out.

**Comment by et1975** [comment]
@forki Please see if elmish@0.8.1 works for you.

**Comment by forki** [comment]
Works like a charm.
Thank you sir!
