### ISSUE TITLE
Elmish for WebSharper apps

### ISSUE THREAD

**Issue by granicz** [fable-compiler/fable-elmish#263]
I was looking into compiling Elmish with WebSharper and it seems pretty straightforward. What is the recommended way to contribute that back to this repo?

**Comment by et1975** [comment]
If it's just a project/settings sort of thing a PR into v4 branch.
If it introduces rendering specifics, then it would need a separate repo,
like we have for "react".
If it needs certain platform support, then it's more like "browser".

**Comment by granicz** [comment]
Cool, thanks - no rendering specifics or extra platform code, just enabling Elmish to be incorporated into WebSharper apps - so a PR into v4 sounds like the way to go. It would be an extra project file that references the existing `.fs` files from `src` and one additional `.fs` file. I can also plug in creating a new `WebSharper.Elmish` package along with the current `Elmish` and `Fable.Elmish` ones.

Given that Fable.Elmish is baked into `src` files via `#IF FABLE_COMPILER` directives, would it make sense to add the above under `src/WebSharper` or under `netstandard/WebSharper`? The latter might work better.

**Comment by et1975** [comment]
Thanks Adam, released as 4.0.0-beta-6.

**Comment by granicz** [comment]
Thanks @et1975 !
