### ISSUE TITLE
Question about FSharp.Core version

### ISSUE THREAD

**Issue by JordanMarr** [fable-compiler/fable-elmish#267]
### Description

I recently submitted a [PR](https://github.com/elmish/Elmish.WPF/pull/551) to the Elmish.WPF repo to update it to use Elmish v4.
There is some confusion in the PR thread as to why the Elmish source code shows FSharp.Core v4.7.*, but the final calculated dependency is actually 6.0.7 as displayed on NuGet. I was hoping to get some clarification on why that is so we can get this PR merged. More specifically, what is causing it to be higher than what is set in the code and is it intentional.

Thanks!

**Comment by et1975** [comment]
I think it's similar to what I described here:
https://github.com/dotnet/fsharp/issues/14441

**Comment by et1975** [comment]
Try `<DisableImplicitFSharpCoreReference>True</DisableImplicitFSharpCoreReference>` and see if you get sensible results by building the package and examining its dependencies?
If you like what you get open a PR.

**Comment by JordanMarr** [comment]
Thank you. I added that and then previewed the NuGet dependencies on the package upload preview page. It removed `FSharp.Core` from the dependencies list altogether (which I suppose is the intended outcome). That seems (at least to me) to be an acceptable path forward.

**Comment by et1975** [comment]
Try using the package in the solution where Fsharp.Core 6 is not added, if that doesn't crash then lets go ahead with the PR.
