### ISSUE TITLE
Cmd.OfFunc.whatever

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/fable-elmish#269]
Dear Elmish gurus,
is there a better way to do this?
```fs
        let whatever (task: 'args -> _) (a: 'args) =
            [ fun d ->
                  try
                      task a |> ignore
                  with
                  | _ -> () ]
```
No message will be dispatched upon success or failure, and seems to complement the existing "perform", "either" and "attempt" functions.

**Comment by davedawkins** [comment]
Perhaps this is what `Cmd.ofEffect` is for

**Comment by MangelMaxime** [comment]
In my project I often add a similar helpers and more.

*The code is the same as yours just using the same structure as Elmish code base*

I call it `Cmd.OfFunc.exec`:

```fs
module Elmish

open Elmish

module Cmd =

    module OfFunc =

        let exec
            (task: 'a -> _)
            (arg: 'a) : Cmd<'msg> =

            let bind _dispatch =
                try
                    task arg
                with x ->
                    ()

            [ bind ]

	// Other variants for Async, Promise, etc.

```

@et1975 We can probably add such variant to Elmish core what do you think?

**Comment by et1975** [comment]
if you don't care about either outcome, why bother involving elmish at all? Just invoke whatever you have yourself, no?

**Comment by davedawkins** [comment]
That wouldn't be executed after the model has been updated, and therefore the view etc.

**Comment by davedawkins** [comment]
To be clear - I'm working on Sutil's implementation of Elmish, and I don't want to introduce any new ideas into Sutil's Elmish that don't map back to ideas and concepts defined in this (master) repo.  I'm saying this so you can judge the priority of the proposal accordingly.

**Comment by MangelMaxime** [comment]
I think I do it this way to have a similar looking code everywhere.

Like that all the "side effects" are triggered in the `Cmd.XXX.YYY` portion of the code. 

It also happens after the model has been updated.

**Comment by et1975** [comment]
Those use-cases seem perfectly valid to me and you absolutely should have them supported in your prelude (library or application). But I think from conceptual/elmish perspective the commands are a way to feed results back into update loop. Which is why I don't think we should enshrine commands as something like delayed execution mechanism.

@kspeakman what's your take on this?

**Comment by kspeakman** [comment]
@et1975 TLDR; I agree with you to leave it out as not encouraged usage. It can be added in user space as needed.

I agree with @MangelMaxime that these side effects (ones triggered from `update`) belong as Cmds. In these rare cases, I typically dispatch a no-op return Msg. Logging for example. `| Logged -> model, Cmd.none`. That way I can see in the Msg log that it happened and the timing relative to other Msgs.

_It is worth noting: Elm's internal API does not permit the usage in question.. A Task must return a single Msg._

Please feel free to poke holes in my reasoning, provide counter examples where these strategies are untenable, etc. If I'm missing something I would love to learn about it.

**Comment by davedawkins** [comment]
>  But I think from conceptual/elmish perspective the commands are a way to feed results back into update loop.

I'm certainly not an Elm(ish) expert, but to me that's not quite a rich enough definition. They're also a way to create side-effects at a certain point in the program loop (ie, after the model update). 

>  It can be added in user space as needed.

This feels like acknowledging the requirement but then falling short of fulfilling that requirement. 

> typically dispatch a no-op return Msg

Yes - this works, and is how I've done this in the past;  from a diagnostic view point it makes a lot of sense (when tracing messages).

I can't help thinking that when one allows perform, attempt and Cmd.ofEffect, you have already prompted for the inclusion of Cmd.OfFunc.exec - they all ignore certain outcomes (mostly exceptions).

Having said all of this, I'm happy with whatever the outcome is - it's been an interesting discussion that I've appreciated reading.

**Comment by kspeakman** [comment]
> I can't help thinking that when one allows perform, attempt and Cmd.ofEffect, you have already prompted for the inclusion of Cmd.OfFunc.exec - they all ignore certain outcomes (mostly exceptions).

You make some good points. For context. The Cmd API permits not returning a msg. Which may make it appear that this is a good option. However, the choice of using dispatch is more of a pragmatic one. It's much easier to integrate with multiple UI platforms. There is another issue discussing ways to remove dispatch from the Elmish API without breaking the world. No solutions as yet.

I believe the fns you mentioned were inspired by Elm's [Task API](https://package.elm-lang.org/packages/elm/core/latest/Task). The difference being that F# doesn't tightly restrict side effects as Elm does. Anything can throw. A safe default is for failing side effects to not crash the app. So all these fns wrap the provided fn in a try catch just in case.

To your point, this does change the semantic meaning of `perform` for example. In Elm it indicates "this can't fail" (which Elm enforces), but in F#/Elmish it effectively means "ignore failures". Which happens to make it suitable only for code that can't fail.
