### ISSUE TITLE
Docs: String.replicate piece raises an exception

### ISSUE THREAD

**Issue by mrakgr** [fable-compiler/fable-elmish#270]
In particular in: https://elmish.github.io/elmish/docs/subscription.html#ids-and-dependencies

```fs
                                        Html.div [
                                            prop.key (string now.Ticks)
                                            let timestampStr =
                                                let s = now.ToString("yyyy-MM-dd HH:mm:ss.ffff")
                                                let zeros = 23 - s.Length
                                                s + String.replicate zeros "0"
                                            prop.text timestampStr
                                        ]
```

As `now.ToString("yyyy-MM-dd HH:mm:ss.ffff")` is of length 24, running this would give out errors in the browser console. Best fix would be to do it like:

```fs
                                        Html.div [
                                            prop.key (string now.Ticks)
                                            let timestampStr = now.ToString("yyyy-MM-dd HH:mm:ss.ffff")
                                            prop.text timestampStr
                                        ]
```

I tried making an edit myself, but I am confused as to where the main site docs are supposed to be in the latest branch. Also, I am sure you are aware of this, but all the example runners are missing `|> Program.withReactBatched "app"`. Yesterday I had a lot of trouble figuring out that I also need to add a `<div id="app">` element `index.html`'s body.

**Comment by MangelMaxime** [comment]
@mrakgr You can click the `Edit` button at the top of the page to be redirected to the Github repo in edition mode.

Otherwise, the documentation is located under the `docs` folder in the current repository and on branch `v.4.x` which is the main branch currently.
