### ISSUE TITLE
Remove redundant Subscription trace logs

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/fable-elmish#272]
### Description

https://github.com/elmish/elmish/blob/852054a7560db6d758cfcc31863d151e49e82b8e/src/program.fs#L79

Regarding this line, I think we should prevent printing any message if there is no subscription. We should also filter out the subscription named 'debugger' which refers to the elmish debugger

**Comment by kspeakman** [comment]
I'm curious to hear others' feedback.

My thinking is: printing no subscriptions is also helpful debugging information. So you can see when subscriptions turn off. Or that there are no subscriptions when you think there should be. Not printing empty subscriptions would leave doubt.

Edit: Perhaps if `withSubscription` is not called, it makes sense to leave subscription logging off.

Edit 2: I'll familiarize myself with the debugger subscription before commenting on that.

**Comment by et1975** [comment]
> Perhaps if withSubscription is not called, it makes sense to leave subscription logging off.

(+)1

But also... maybe complicated, but only log if there's difference?

**Comment by AlbertoDePena** [comment]
I like the idea of no log if `withSubscription` is not called

**Comment by AlbertoDePena** [comment]
Hello, lovely FSharpers... Have a decision been made on the redundant logs? Thanks =)

**Comment by et1975** [comment]
@AlbertoDePena Feel free to PR this so we can see what it looks like.

**Comment by AlbertoDePena** [comment]
@et1975 

I actually submitted a PR to the `Tracers.console` for the `browser` library.

https://github.com/elmish/browser/pull/65

**Comment by MangelMaxime** [comment]
Should this be closed?

I am asking as the PR linked above has been merge or is there something else that we need to do?
