### ISSUE TITLE
Suggestion: Cmd.OfTask.attempt with untyped Task

### ISSUE THREAD

**Issue by Tarmil** [fable-compiler/fable-elmish#276]
### Description

It is a bit inconvenient to attempt a `Task` (without type parameter) as a command.

```fsharp
let doSomething arg = Task.CompletedTask // a dummy Task

Cmd.OfTask.attempt (fun x -> task { return! doSomething x }) arg Error
// or:
Cmd.OfAsync.attempt (doSomething >> Async.AwaitTask) arg Error
```

If `Cmd.OfTask.attempt` took a function `_ -> #Task` rather than `_ -> Task<_>`, then it would be simpler:

```fsharp
Cmd.OfTask.attempt doSomething arg Error
```

and still compatible with current uses, since `Task<_>` inherits from `Task`.

**Comment by et1975** [comment]
Makes sense, open to a PR.
