### ISSUE TITLE
How to dispose of `Cmd.ofEffect` events handler?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-elmish#279]
### Description

Hello @kspeakman, 

Today I had the opportunity to play a bit with the new `Effect` system and was able to create an `Effect` which listen to the `click` event (see the code at the end of this issue).

However, I am wondering if it is possible to dispose of the `event handler` from inside an Elmish component. I have 2 scenarios in mind:

1. Have the event listened to only once and then disposed
2. Have the event listened to for has long as I want and then decide to cancel it based on a condition for example

I am aware of the [conditional-subscriptions](https://elmish.github.io/elmish/docs/subscription.html#conditional-subscriptions) section on the Elmish documentation but it requires to be done at the program level. Meaning that it is not really scalable because I would have to dig deep into the model and also would only work for a specific Model so it can't be made as a library (unless I missed something).

```fs
module App

open Feliz
open Fable.Core.JsInterop
open Browser
open Feliz.UseElmish
open Elmish
open Browser.Dom
open System

// Workaround to have React-refresh working
// I need to open an issue on react-refresh to see if they can improve the detection
emitJsStatement () "import React from \"react\""

type private Model =
    {
        MouseX : float
        MouseY : float
    }

type private Msg =
    | MouseDown of float * float

module Effect =

    module Mouse =

        let down (tag : (float * float) -> 'Msg) : Effect<'Msg> =
            let effectFn dispatch =
                window.addEventListener("click", fun ev ->
                    let ev = ev :?> Types.MouseEvent
                    (ev.x,ev.y)
                    |> tag
                    |> dispatch
                )

            effectFn

let private init () =
    {
        MouseX = 0
        MouseY = 0
    }
    , Cmd.ofEffect (Effect.Mouse.down MouseDown)

let private update msg model =
    match msg with
    | MouseDown (mouseX, mouseY) ->
        { model with
            MouseX = mouseX
            MouseY = mouseY
        }
        , Cmd.none

[<ReactComponent>]
let App () =
    let createProgram () =
        Program.mkProgram init update (fun _ _ -> ())

    let model, dispatch = React.useElmish(createProgram)


    Html.div [
        Html.text $"Mouse position: {model.MouseX}, {model.MouseY}"
        Html.br [ ]
        Html.text "Click to update mouse position"
    ]
```

**Comment by kspeakman** [comment]
Hey @MangelMaxime,

From the JS side, `addEventListener` has options to make it only run [once](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#once) or stop listening when it receives a [signal](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#signal).

From the Elmish side, these are good use cases for subscriptions. Or even for `view` if the event handler needs to be attached to a UI element. Yes, the wiring is a bit inelegant as a library function. The library user would need to plug in the library at several points: subscribe, update, msg case.

It's possible to run a subscription as a headless MVU app underneath. Since it runs independently of the user's app. We don't currently have an API for that. I believe Elm does.

**Comment by MangelMaxime** [comment]
> From the JS side, addEventListener has options to make it only run [once](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#once) or stop listening when it receives a [signal](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#signal).

Right, I forgot about this feature

> The library user would need to plug in the library at several points: subscribe, update, msg case.

Looking at the documentation again, it means that we could provide `Effect.Mouse.down`, `Effect.Timer.every`, etc.

And the user could use them directly from `Cmd.ofEffect` or if he needs conditional effect he would "just" need to write the `subscribe` function based on those effect.

>  I believe Elm does.

I believe in the past Elm was able to stop effect from within a component but I can't find it again. It is possible that it was removed with Elm 0.19 has that version broke (changed) a lot of stuff.

I will close this issue for now, as I was mostly checking if I missed something or not. And already have enough project on hand to not create a new library ahah
