### ISSUE TITLE
Racing condition in Elmish loop with Async and Task Cmd.

### ISSUE THREAD

**Issue by ed-ilyin** [fable-compiler/fable-elmish#286]
## Description
I'm encountering a race condition in my Elmish application involving Ring's Pushes and Pops and a reentered mutable variable. The issue occurs when a dispatch happens between Pop -> None and reentered <- false, causing the application to stop functioning properly.

## Repro Code
I've created a minimal reproduction repository that demonstrates the issue. You can find it here: [elmish-race](https://github.com/ed-ilyin/elmish-race).

## Expected and Actual Results
- **Expected Result**: The application should exit normally after processing the trade.
- **Actual Result**: The application enters a limbo state and stops functioning correctly, demonstrating a race condition.

## Logs
Here are the logs from the application showing the sequence of events leading to the issue:
```
Enter Process with: Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.00048M, IsBuyerMaker = true }
Popping: Some (Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.00048M, IsBuyerMaker = true })
Process loop started with Some (Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.00048M, IsBuyerMaker = true })
Processing: Some (Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.00048M, IsBuyerMaker = true })
Popping: None
Dispatching: Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.0003M, IsBuyerMaker = true }
Pushing: Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.0003M, IsBuyerMaker = true }
Process loop ended with None
Reentered dispatch loop with: Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.0003M, IsBuyerMaker = true }
Exit Process with: Trade { Time = 5/19/2024 4:53:49 PM +00:00, Price = 66713.68M, Quantity = 0.00048M, IsBuyerMaker = true }
```

## Observations
- The issue does not occur every time but can be reproduced by running the application multiple times.
- Using `Cmd.OfAsyncImmediate` instead of `Cmd.OfTask` or `Cmd.OfAsync` resolves the race condition.

## Related Information
- **Elmish version**: 4.1.0
- **fable-compiler version**: N/A (pure .NET)
- **fable-core version**: N/A (pure .NET)
- **Operating system**: macOS Sonoma 14.4.1 @ M1 Max, Windows 11 Arm @ Parallels

## Additional Context
I've been discussing this issue on Gitter and have provided a minimal reproduction repository. Any insights or guidance on resolving this race condition would be greatly appreciated.

Thank you!

**Comment by et1975** [comment]
Yes, the ring is not thread safe, that's why every elmish program targeting
a runtime where multithreading exists the dispatch function is wrapped in
some sort of synchronization mechanism. See WPF for example.

**Comment by et1975** [comment]
Use `runWithDispatch` instead of `run` and supply your own queueing mechanism.
