### ISSUE TITLE
Cmd.none should restrict type to Cmd 

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-elmish#29]

**Comment by et1975** [comment]
Probably, event though `[]` is a well known shorthand :/

**Comment by et1975** [comment]
wait, it does!
https://github.com/fable-compiler/fable-elmish/blob/master/src/elmish/elmish.fs#L17

**Comment by forki** [comment]
Ok cool. Then my type inference went rogue for other reasons. Thanks for
checking.

Am 26.01.2017 15:00 schrieb "Eugene Tolmachev" <notifications@github.com>:
