### ISSUE TITLE
error FS0039: The namespace 'Elmish' is not defined

### ISSUE THREAD

**Issue by dotnetspec** [fable-compiler/fable-elmish#291]
### Description
I get the above error when I attempt to build the project. I am new to F#. I have installed F# and successfully built a Simple.fs file (included below) and I am now trying to build a 'HwareConnect.fs' file as well. The build fails on line 3:
`open Fable.Elmish`

### Repro code

```
dotnet add package Fable.Elmish --version 4.2.0
dotnet clean
dotnet restore
dotnet build
```

the relevant files are here (I only included Simple.fs to illustrate that I have the basic F# setup/compiling successfully):
[FS0039 error.zip](https://github.com/user-attachments/files/16192684/FS0039.error.zip)

### Expected and actual results

Expected result:
```
dotnet build
  Determining projects to restore...
  All projects are up-to-date for restore.
  haveno-ui -> ~haveno-dex/haveno-ui/packages/renderer/src/components/fsharpcomponents/bin/Debug/net8.0/haveno-ui.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.52
```

Actual result:
`error FS0039: The namespace 'Elmish' is not defined`

### Related information 

* elmish version: 4.2.0
* fable-compiler version: 2.13.0
* fable-core version: 4.3.0
* Operating system: Linux Mint 21.3 Cinnamon

**Comment by MangelMaxime** [comment]
Hello,

you need to use `open Elmish` and not `open Fable.Elmish` to access Elmish APIs.

Feel free to re-open if needed.

**Comment by dotnetspec** [comment]
That was it, thanks.
So is [Fable.Elmish](https://www.nuget.org/packages/Fable.Elmish#readme-body-tab) now deprecated?

**Comment by MangelMaxime** [comment]
No it isn't.

In F#, the name of package and the name of the namespace are not related.

You can name you package `MySuperPackage` but use the `open MySuperLibrary` for the namespaces.

`Fable.Elmish` is the package to use when targeting Fable runtime while `Elmish` package is to be used when targeting .NET
