### ISSUE TITLE
The value, constructor, namespace or type 'withReactBatched' is not defined.

### ISSUE THREAD

**Issue by dotnetspec** [fable-compiler/fable-elmish#292]
### Description

Compilation error when attempting to create a React component from an F# file following the [tutorial](https://elmish.github.io/react/tutorials/browser.html).

### Repro code

`fable --lang ts`

[tutorial error.zip](https://github.com/user-attachments/files/16231285/tutorial.error.zip)

### Expected:
```
Started Fable compilation...
Compiled 22/22: HwareConnect.fs                                                     
Fable compilation finished in ... ms
<No Errors>
```

### Actual:
```
Started Fable compilation...
Compiled 22/22: HwareConnect.fs                                                     
Fable compilation finished in 3775ms

./HwareConnect.fs(34,12): (34,28) error FSHARP: The value, constructor, namespace or type 'withReactBatched' is not defined. Maybe you want one of the following:   withTrace   withSetState (code 39)
Compilation failed
```

### Related information 
    elmish version: 4.2.0
    fable-compiler version: 2.13.0
    fable-core version: 4.3.0
    Operating system: Linux Mint 21.3 Cinnamon

I have tried withTrace and withSetState, which get similar error messages. What should I change to enable the component to be created? thanks ...

**Comment by MangelMaxime** [comment]
You need to open `Elmish.React` like shown in the tutorial.

```fs
open Elmish.React

Program.mkSimple init update view
|> Program.withReactBatched "elmish-app"
|> Program.run
```
