### ISSUE TITLE
Any documentation or sample for using a subscription?

### ISSUE THREAD

**Issue by 7sharp9** [fable-compiler/fable-elmish#3]

**Comment by et1975** [comment]
My fork has `parent-child` sample for ReactNative in `dev` branch. Originally a test bed for all the features the code still has a Subscription as well as an example of a Task.

**Comment by 7sharp9** [comment]
Thanks for the info, Is it possible to map subscriptions in the current api, I could only see command map?

**Comment by et1975** [comment]
I'm sure there's a good reason, but I couldn't see the point of Elm's distinction between `Sub` and `Cmd`, so you should be able to use `Cmd.map`. Although I think that what you might actually need is a way to transform the `dispatch` function like #1 describes.

If you see `Sub` abstraction as a must have, I'm open to adding it.

**Comment by 7sharp9** [comment]
Yeah I want to map one subscription onto another like this:
https://github.com/elm-lang/navigation/blob/master/src/Navigation.elm#L71-L75

**Comment by et1975** [comment]
I think https://github.com/et1975/fable-elmish/blob/dev/samples/react-native/parent-child/src/State.fs#L19 does exactly that. You can also `Cmd.batch` your subscriptions the same way as elm navigation does.

**Comment by Banashek** [comment]
I believe https://github.com/fable-compiler/fable-elmish/tree/master/samples/react-native/subscription should cover this.

Perhaps we can close this issue out and create another for navigation?

**Comment by Banashek** [comment]
Though admittedly I should stop just adding examples for react-native, and translate those all over into the react samples as well. I'll get to that as soon as I have some time.

**Comment by et1975** [comment]
Navigation is in, closing.
