### ISSUE TITLE
[fable-elmish@next + fable-elmish-snabbdom@next] problems with Fable.Import and Result

### ISSUE THREAD

**Issue by jmmk** [fable-compiler/fable-elmish#47]
A few things I encountered when trying to get running on Fable 1.0:

- `node_modules/fable-elmish-snabbdom/Fable.Import.Snabbdom.fs(L1,13) : error FSHARP: A namespace and a module named 'Fable.Import' both occur in two parts of this assembly`

I think this is caused by the use of `module Fable.Import` inside `Fable.Import.Snabbdom.fs` instead of using `namespace Fable.Import`.

- the `Result` type from `result.fs` inside Elmish conflicts with F#'s `Result`

**Comment by MangelMaxime** [comment]
Hello @jmmk the problem for `Fable.Import.Snabbdom` should be fixed in version `0.9.0-beta-5`

**Comment by et1975** [comment]
> the Result type from result.fs inside Elmish conflicts with F#'s Result
We wouldn't have had a single successful build if that was the case, but regardless I'm deprecating `Result` type.

**Comment by MangelMaxime** [comment]
Yes this is what is surprising me about this bug. But I am having the same problem on my computer at the moment.

**Comment by jmmk** [comment]
Fable.Import.Snabbdom seems to be fine now. 👍 

As for `Result`, I'm not sure exactly what state I had things in, but without ever explicity opening `Elmish.Result` the compiler saw it in conflict with `Fsharp.Core.Result` and/or `PowerPack.Result` when I was trying to pattern match `OK v`

**Comment by et1975** [comment]
I'm seeing something similar with another type, looks like a new constraint from Fable.

**Comment by jmmk** [comment]
@et1975 You're correct about disambiguating type collisions, but I wouldn't expect `open Elmish` to override anything from `FSharp.Core`

Will close since it looks like things have been moved around and it should no longer be an issue
