### ISSUE TITLE
What is snabbdom?

### ISSUE THREAD

**Issue by Kurren123** [fable-compiler/fable-elmish#54]
Hi

Love F#, new to Fable Elmish. What is snabbdom? Which is better for production, react or snabbdom? 

Thanks

**Comment by et1975** [comment]
@MangelMaxime might explain it better, but essentially it's [lightweight DOM](https://github.com/snabbdom/snabbdom). Wether it's "better" than React would depend on your requirements: React's got bigger ecosystem, but it's quite a bit heavier.

**Comment by Kurren123** [comment]
Perfect thanks

**Comment by MangelMaxime** [comment]
@Kurren123 Sorry for the late answer, as @et1975 said snabbdom is a lightweight DOM.

If we speak from Elmish point of view, this is another renderer/DSL offered to the user.
For example, Elmish-Snabbdom make a difference between an event declaration and a property one.

Elmish-React:
```fs
let viewControlsClear entriesCompleted dispatch =
  R.button
    [ ClassName "clear-completed"
      Hidden (entriesCompleted = 0)
      OnClick (fun _ -> DeleteComplete |> dispatch)]
    [ R.str ("Clear completed (" + (string entriesCompleted) + ")") ]
```

Elmish-Snabbdom:

```fs
let viewControlsClear entriesCompleted dispatch =
  button
    [ props [
        ClassName "clear-completed"
        Hidden (entriesCompleted = 0)
      ]
      events [
        OnClick (fun _ -> DeleteComplete |> dispatch)
      ]
    ]
    [ str ("Clear completed (" + (string entriesCompleted) + ")") ]
```

As you can see Snabbdom version is a little more verbose. This lead to a more precise intellisense but in the end it's mostly a matter of personnal preference.
