### ISSUE TITLE
None of the samples work under windows with Fable 1.0

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/fable-elmish#65]
### Description

I have .net core 1.0.1 installed with fable 1.0 but non of the samples work. First problem is those instructions popd etc are *nix specific Even without them the build process fails with some erros like : 
 Restoring packages for C:\Users\onur\Projects\Fable\fable-elmish-master\samples\react\todomvc\app.fsproj...
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Unable to resolve 'C:\Users\onur\Projects\Fable\fable-elmish-master\samples\react\node_modules\fable-powerpack\Fable.PowerPack.fsproj' for '.NETStandard,Version=v1.6'. [C:\Users\onur\Projects\Fable\fable-elmish-master\samples\react\todomvc\app.fsproj]

**Comment by MangelMaxime** [comment]
Hello @OnurGumus 

Seems like you didn't installed the package needed by the samples.
In the folder `samples/react` execute the command `yarn install` or `npm install`.
From there you can do follow the samples instructions 2, 3, 4.

If you still have problem feel free to comment :)

I am renaming your issue to better match the problem :)

**Comment by OnurGumus** [comment]
@MangelMaxime you are correct. I should have run yarn install in an upper folder. Note that on windows there is no pushd. So having separate instructions for windows  might be helpful.
Thanks help.

**Comment by et1975** [comment]
Pushd is there, so is popd.

**Comment by OnurGumus** [comment]
You are again correct! I need to check what is wrong with my typing :)

**Comment by OnurGumus** [comment]
Ok for the push and popd, the actual problem was && and I was using powershell and && is not supported there. With cmd it's fine.
