### ISSUE TITLE
Fable compiler message when compiling example todomvc

### ISSUE THREAD

**Issue by EdouardM** [fable-compiler/fable-elmish#7]
Hello, 

I cloned repo and try to compile the sample in available at: 
https://github.com/fable-compiler/fable-elmish/tree/master/samples/react/todomvc

I did: 
1) npm install
2) fable todomvc.fsx

Fable compiler returns: 
"Cannot find replacement for Microsoft.FSharp.Control.MailBoxProcessor.receive at ...\elmish.fs (100,31 - 110, 43)"

This prevents the compiler from finishing to create the file: todomvc.fs in out/ directory. So I can't run the sample.

Thanks in advance for your help;
Edouard

**Comment by et1975** [comment]
can you give more info about the environment? It should be compiling.

**Comment by EdouardM** [comment]
Here are following environment information: 
- OS : Windows 10
- IDE: VS Code 1.5.3
- Node: 5.10
In the todomvc folder I did 'npm ls' command:
- core-js@2.4.1
- fable-core@0.6.6
- fable-elmish@0.3.0
- fable-import-react@0.5.2
- react@15.3.2
- react-hot-loader@1.3.0
- source-map-loader@0.1.5
- todomvc-app-css@2.0.6
- todomvc-common@1.0.2
- webpack@1.13.2
- webpack-dev-server@1.16.1

Please ask for more details if needed.

**Comment by et1975** [comment]
I am unable to reproduce, here's my build on a fresh checkout in the same environment:

>C:\sources\fable-elmish\samples\react\todomvc>fable
npm install
fable-elmish-todomvc@1.0.0 C:\sources\fable-elmish\samples\react\todomvc
+-- core-js@2.4.1
+-- fable-core@0.6.6
+-- fable-elmish@0.3.0
+-- fable-import-react@0.5.2
+-- react@15.3.2
| +-- fbjs@0.8.5
| | +-- core-js@1.2.7
| | +-- immutable@3.8.1
| | +-- isomorphic-fetch@2.2.1
| | | +-- node-fetch@1.6.3
| | | | +-- encoding@0.1.12
| | | | | `-- iconv-lite@0.4.13
| | | | `-- is-stream@1.1.0
| | | `-- whatwg-fetch@1.0.0
| | +-- promise@7.1.1
| | | `-- asap@2.0.5
| | `-- ua-parser-js@0.7.10
| +-- loose-envify@1.2.0
| | `-- js-tokens@1.0.3
| `-- object-assign@4.1.0
+-- react-dom@15.3.2
+-- react-hot-loader@1.3.0
| +-- react-hot-api@0.4.7
| `-- source-map@0.4.4
|   `-- amdefine@1.0.0
+-- source-map-loader@0.1.5
| +-- async@0.9.2
| +-- loader-utils@0.2.16
| | +-- big.js@3.1.3
| | +-- emojis-list@2.0.1
| | `-- json5@0.5.0
| `-- source-map@0.1.43
+-- todomvc-app-css@2.0.6
+-- todomvc-common@1.0.2
+-- webpack@1.13.2
| +-- acorn@3.3.0
| +-- async@1.5.2
| +-- clone@1.0.2
| +-- enhanced-resolve@0.9.1
| | +-- graceful-fs@4.1.9
| | `-- memory-fs@0.2.0
| +-- interpret@0.6.6
| +-- memory-fs@0.3.0
| | +-- errno@0.1.4
| | | `-- prr@0.0.0
| | `-- readable-stream@2.1.5
| |   +-- buffer-shims@1.0.0
| |   +-- core-util-is@1.0.2
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@1.0.7
| |   `-- util-deprecate@1.0.2
| +-- mkdirp@0.5.1
| | `-- minimist@0.0.8
| +-- node-libs-browser@0.6.0
| | +-- assert@1.4.1
| | +-- browserify-zlib@0.1.4
| | | `-- pako@0.2.9
| | +-- buffer@4.9.1
| | | +-- base64-js@1.2.0
| | | `-- ieee754@1.1.6
| | +-- console-browserify@1.1.0
| | | `-- date-now@0.1.4
| | +-- constants-browserify@0.0.1
| | +-- crypto-browserify@3.2.8
| | | +-- pbkdf2-compat@2.0.1
| | | +-- ripemd160@0.2.0
| | | `-- sha.js@2.2.6
| | +-- domain-browser@1.1.7
| | +-- events@1.1.1
| | +-- http-browserify@1.7.0
| | | `-- Base64@0.2.1
| | +-- https-browserify@0.0.0
| | +-- os-browserify@0.1.2
| | +-- path-browserify@0.0.0
| | +-- process@0.11.9
| | +-- punycode@1.4.1
| | +-- querystring-es3@0.2.1
| | +-- readable-stream@1.1.14
| | | `-- isarray@0.0.1
| | +-- stream-browserify@1.0.0
| | | `-- readable-stream@1.1.14
| | |   `-- isarray@0.0.1
| | +-- string_decoder@0.10.31
| | +-- timers-browserify@1.4.2
| | +-- tty-browserify@0.0.0
| | +-- url@0.10.3
| | | +-- punycode@1.3.2
| | | `-- querystring@0.2.0
| | +-- util@0.10.3
| | | `-- inherits@2.0.1
| | `-- vm-browserify@0.0.4
| |   `-- indexof@0.0.1
| +-- optimist@0.6.1
| | `-- wordwrap@0.0.3
| +-- supports-color@3.1.2
| | `-- has-flag@1.0.0
| +-- tapable@0.1.10
| +-- uglify-js@2.6.4
| | +-- async@0.2.10
| | +-- source-map@0.5.6
| | +-- uglify-to-browserify@1.0.2
| | `-- yargs@3.10.0
| |   +-- camelcase@1.2.1
| |   +-- cliui@2.1.0
| |   | +-- center-align@0.1.3
| |   | | +-- align-text@0.1.4
| |   | | | +-- longest@1.0.1
| |   | | | `-- repeat-string@1.5.4
| |   | | `-- lazy-cache@1.0.4
| |   | +-- right-align@0.1.3
| |   | `-- wordwrap@0.0.2
| |   +-- decamelize@1.2.0
| |   `-- window-size@0.1.0
| +-- watchpack@0.2.9
| | `-- chokidar@1.6.0
| |   +-- anymatch@1.3.0
| |   | `-- arrify@1.0.1
| |   +-- async-each@1.0.1
| |   +-- glob-parent@2.0.0
| |   +-- is-binary-path@1.0.1
| |   | `-- binary-extensions@1.6.0
| |   +-- is-glob@2.0.1
| |   `-- readdirp@2.1.0
| |     +-- minimatch@3.0.3
| |     | `-- brace-expansion@1.1.6
| |     |   +-- balanced-match@0.4.2
| |     |   `-- concat-map@0.0.1
| |     `-- set-immediate-shim@1.0.1
| `-- webpack-core@0.6.8
|   `-- source-list-map@0.1.6
`-- webpack-dev-server@1.16.1
  +-- compression@1.6.2
  | +-- accepts@1.3.3
  | | `-- negotiator@0.6.1
  | +-- bytes@2.3.0
  | +-- compressible@2.0.8
  | | `-- mime-db@1.24.0
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | +-- on-headers@1.0.1
  | `-- vary@1.1.0
  +-- connect-history-api-fallback@1.3.0
  +-- express@4.14.0
  | +-- array-flatten@1.1.1
  | +-- content-disposition@0.5.1
  | +-- content-type@1.0.2
  | +-- cookie@0.3.1
  | +-- cookie-signature@1.0.6
  | +-- depd@1.1.0
  | +-- encodeurl@1.0.1
  | +-- escape-html@1.0.3
  | +-- etag@1.7.0
  | +-- finalhandler@0.5.0
  | | +-- statuses@1.3.0
  | | `-- unpipe@1.0.0
  | +-- fresh@0.3.0
  | +-- merge-descriptors@1.0.1
  | +-- methods@1.1.2
  | +-- on-finished@2.3.0
  | | `-- ee-first@1.1.1
  | +-- parseurl@1.3.1
  | +-- path-to-regexp@0.1.7
  | +-- proxy-addr@1.1.2
  | | +-- forwarded@0.1.0
  | | `-- ipaddr.js@1.1.1
  | +-- qs@6.2.0
  | +-- range-parser@1.2.0
  | +-- send@0.14.1
  | | `-- destroy@1.0.4
  | +-- serve-static@1.11.1
  | +-- type-is@1.6.13
  | | `-- media-typer@0.3.0
  | `-- utils-merge@1.0.0
  +-- http-proxy-middleware@0.17.2
  | +-- http-proxy@1.15.1
  | | +-- eventemitter3@1.2.0
  | | `-- requires-port@1.0.0
  | +-- is-glob@3.0.0
  | | `-- is-extglob@2.0.0
  | +-- lodash@4.16.2
  | `-- micromatch@2.3.11
  |   +-- arr-diff@2.0.0
  |   | `-- arr-flatten@1.0.1
  |   +-- array-unique@0.2.1
  |   +-- braces@1.8.5
  |   | +-- expand-range@1.8.2
  |   | | `-- fill-range@2.2.3
  |   | |   +-- is-number@2.1.0
  |   | |   +-- isobject@2.1.0
  |   | |   `-- randomatic@1.1.5
  |   | +-- preserve@0.2.0
  |   | `-- repeat-element@1.1.2
  |   +-- expand-brackets@0.1.5
  |   | `-- is-posix-bracket@0.1.1
  |   +-- extglob@0.3.2
  |   +-- filename-regex@2.0.0
  |   +-- is-extglob@1.0.0
  |   +-- kind-of@3.0.4
  |   | `-- is-buffer@1.1.4
  |   +-- normalize-path@2.0.1
  |   +-- object.omit@2.0.0
  |   | +-- for-own@0.1.4
  |   | | `-- for-in@0.1.6
  |   | `-- is-extendable@0.1.1
  |   +-- parse-glob@3.0.4
  |   | +-- glob-base@0.3.0
  |   | `-- is-dotfile@1.0.2
  |   `-- regex-cache@0.4.3
  |     +-- is-equal-shallow@0.1.3
  |     `-- is-primitive@2.0.0
  +-- open@0.0.5
  +-- serve-index@1.8.0
  | +-- batch@0.5.3
  | +-- http-errors@1.5.0
  | | +-- inherits@2.0.1
  | | `-- setprototypeof@1.0.1
  | `-- mime-types@2.1.12
  +-- sockjs@0.3.18
  | +-- faye-websocket@0.10.0
  | | `-- websocket-driver@0.6.5
  | |   `-- websocket-extensions@0.1.1
  | `-- uuid@2.0.3
  +-- sockjs-client@1.1.1
  | +-- eventsource@0.1.6
  | | `-- original@1.0.0
  | |   `-- url-parse@1.0.5
  | +-- faye-websocket@0.11.0
  | +-- inherits@2.0.3
  | +-- json3@3.3.2
  | `-- url-parse@1.1.3
  |   `-- querystringify@0.0.4
  +-- stream-cache@0.0.2
  +-- strip-ansi@3.0.1
  | `-- ansi-regex@2.0.0
  `-- webpack-dev-middleware@1.8.3
    +-- mime@1.3.4
    `-- path-is-absolute@1.0.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
fable-compiler 0.6.8: Start compilation...
Compiled elmish-1634153869.fs at 4:02:14 PM
Compiled todomvc.fsx at 4:02:15 PM

You may have a better luck asking in fable gitter.
