### ISSUE TITLE
Fable.Template.Elmish.React is shipping with node_modules causing npm install to fail

### ISSUE THREAD

**Issue by richardjharding** [fable-compiler/fable-elmish#77]
Version 0.1.5 of the template is shipping with the node_modules folder populated  - possibly with non windows os content

When following the instructions npm install does not error but on windows the webpack.cmd etc are not present in the node_modules/.bin folder causing the dotnet fable npm-start command to fail with an error complaining that webpack-dev-server cannot be found

Using yarn install instead of npm does correctly re-install the npm packages and the app can be startedas expected

**Comment by MangelMaxime** [comment]
@richardjharding The new nuget version should fix this problem :)
Thanks for reporting it :) and sorry for the problem.
